//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_InditionFinal_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afspraak
    {
        public int afspraak_id { get; set; }
        public int afspraak_klant { get; set; }
        public System.DateTime afspraak_datum { get; set; }
        public string afspraak_nota { get; set; }
    
        public virtual Klant Klant { get; set; }
    }
}
