//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_InditionFinal_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Behandeling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Behandeling()
        {
            this.BehandelingLijn = new HashSet<BehandelingLijn>();
        }
    
        public int behandeling_id { get; set; }
        public int behandeling_klant { get; set; }
        public string behandeling_nota { get; set; }
        public System.DateTime behandeling_datum { get; set; }
        public bool behandeling_isVoorafBehandeld { get; set; }
    
        public virtual Klant Klant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BehandelingLijn> BehandelingLijn { get; set; }
    }
}
