//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_InditionFinal_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehandelingLijn
    {
        public int behandelingLijn_id { get; set; }
        public int behandelingLijn_behandeling { get; set; }
        public int behandelingLijn_product { get; set; }
    
        public virtual Behandeling Behandeling { get; set; }
        public virtual Product Product { get; set; }
    }
}
