//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_InditionFinal_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klant()
        {
            this.Afspraken = new HashSet<Afspraak>();
            this.Behandelingen = new HashSet<Behandeling>();
        }
    
        public int klant_id { get; set; }
        public string klant_voornaam { get; set; }
        public string klant_familienaam { get; set; }
        public string klant_telefoon { get; set; }
        public string klant_e_mail { get; set; }
        public string klant_adres { get; set; }
        public int klant_adresnummer { get; set; }
        public string klant_plaats { get; set; }
        public string klant_postcode { get; set; }
        public bool klant_isArchived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Afspraak> Afspraken { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Behandeling> Behandelingen { get; set; }
    }
}
